### ISSUE TITLE
Problem importing "global" is not defined.

### ISSUE THREAD

**Issue by PixsaOJ** [eriscrypt/connector-plugin#1]
Hi, I simply copied code from example, seems like importing plugin causes this issues:

Warining:
```
browser-external:buffer:9 Module "buffer" has been externalized for browser compatibility. Cannot access "buffer.Buffer" in client code.
get @ browser-external:buffer:9
(anonymous) @ bn.js:56
node_modules/.pnpm/bn.js@5.2.1/node_modules/bn.js/lib/bn.js @ bn.js:3547
__require @ chunk-WFCWLEYV.js?v=170b2fb1:11
node_modules/.pnpm/@ethersproject+bignumber@5.7.0/node_modules/@ethersproject/bignumber/lib.esm/bignumber.js @ bignumber.ts:11
__init @ chunk-WFCWLEYV.js?v=170b2fb1:8
node_modules/.pnpm/@ethersproject+bignumber@5.7.0/node_modules/@ethersproject/bignumber/lib.esm/index.js @ index.ts:1
__init @ chunk-WFCWLEYV.js?v=170b2fb1:8
node_modules/.pnpm/@ethersproject+abi@5.7.0/node_modules/@ethersproject/abi/lib.esm/fragments.js @ fragments.ts:3
__init @ chunk-WFCWLEYV.js?v=170b2fb1:8
node_modules/.pnpm/@ethersproject+abi@5.7.0/node_modules/@ethersproject/abi/lib.esm/index.js @ index.ts:3
__init @ chunk-WFCWLEYV.js?v=170b2fb1:8
node_modules/.pnpm/@ethersproject+contracts@5.7.0/node_modules/@ethersproject/contracts/lib.esm/index.js @ index.ts:3
__init @ chunk-WFCWLEYV.js?v=170b2fb1:8
node_modules/.pnpm/ethers@5.7.2/node_modules/ethers/lib.esm/ethers.js @ ethers.ts:3
__init @ chunk-WFCWLEYV.js?v=170b2fb1:8
node_modules/.pnpm/ethers@5.7.2/node_modules/ethers/lib.esm/index.js @ index.ts:5
__init @ chunk-WFCWLEYV.js?v=170b2fb1:8
node_modules/.pnpm/vue-dapp-connector@2.4.2/node_modules/vue-dapp-connector/dist/index.js @ index.js:15
__require @ chunk-WFCWLEYV.js?v=170b2fb1:11
(anonymous) @ index.js:102
```

And Error:
```
_stream_readable.js:48 Uncaught ReferenceError: global is not defined
    at node_modules/.pnpm/readable-stream@3.6.0/node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:48:21)
    at __require (chunk-WFCWLEYV.js?v=170b2fb1:11:50)
    at node_modules/.pnpm/readable-stream@3.6.0/node_modules/readable-stream/readable-browser.js (readable-browser.js:1:28)
    at __require (chunk-WFCWLEYV.js?v=170b2fb1:11:50)
    at node_modules/.pnpm/keccak@3.0.3/node_modules/keccak/lib/api/keccak.js (keccak.js:1:23)
    at __require (chunk-WFCWLEYV.js?v=170b2fb1:11:50)
    at node_modules/.pnpm/keccak@3.0.3/node_modules/keccak/lib/api/index.js (index.js:1:22)
    at __require (chunk-WFCWLEYV.js?v=170b2fb1:11:50)
    at node_modules/.pnpm/keccak@3.0.3/node_modules/keccak/js.js (js.js:1:18)
    at __require (chunk-WFCWLEYV.js?v=170b2fb1:11:50)
```

Additional info: I am using Vite's vue-ts template.

Problem is happening as soon I import `import { Connector, EVENTS } from "vue-dapp-connector";` I am importing it in my Component not app.

**Comment by PixsaOJ** [comment]
In Vite config, add following: 

```JS
define: {
  "global": "window",
  "process": { env: {} },
},
```
